# Generated by Django 4.1.4 on 2022-12-23 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 9, 9, 4, 432611, tzinfo=datetime.timezone.utc)),
        ),
    ]
