# Generated by Django 4.1.4 on 2022-12-23 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_App', '0002_messages_timesent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='timeSent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
