# Generated by Django 4.1.4 on 2022-12-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_App', '0003_alter_messages_timesent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='timeSent',
        ),
        migrations.AddField(
            model_name='messages',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
