# Generated by Django 4.1.4 on 2022-12-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moderator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportuser',
            name='reportMessage',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
