# Generated by Django 4.1.4 on 2022-12-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dating_Site_App', '0002_alter_profile_dob_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
