# Generated by Django 4.1.4 on 2022-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dating_Site_App', '0004_alter_profile_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
