# Generated by Django 4.1.4 on 2022-12-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dating_Site_App', '0006_alter_profile_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(blank=True, default='/images/DefaultPic.jpg', upload_to='images/'),
        ),
    ]
